CReshetka/Controllers/DataStructureController.cs
using Microsoft.AspNetCore.Mvc;

namespace CReshetka.Controllers
{
    //хеш-таблица
    public class DataStructureController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Array()
        {
            return View();
        }

        public IActionResult List()
        {
            return View();
        }
        
        public IActionResult LinkedList()
        {
            return View();
        }

        public IActionResult Queue()
        {
            return View();
        }

        public IActionResult Stack()
        {
            return View();
        }

        public IActionResult Dictionary()
        {
            return View();
        }

    }
}

CReshetka/Controllers/SearchAlgorithmsController.cs
using Microsoft.AspNetCore.Mvc;

namespace CReshetka.Controllers
{
    public class SearchAlgorithmsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

CReshetka/Controllers/SortAlgorithmsController.cs
using CReshetka.Constants;
using CReshetka.Data;
using CReshetka.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace CReshetka.Controllers
{
    public class SortAlgorithmsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SortAlgorithmsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BubbleSort()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CocktailSort()
        {
            return View();
        }

        [HttpGet]
        public IActionResult InsertionSort()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ShellSort()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult TreeSort()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult HeapSort()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult SelectionSort()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult GnomeSort()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult RadixSort()
        {
            return View();
        } 
        
        [HttpGet]
        public IActionResult MergeSort()
        {
            return View();
        } 
        
        [HttpGet]
        public IActionResult QuickSort()
        {
            return View();
        }


    }
}

CReshetka/Controllers/TestingController.cs
using CReshetka.Data;
using CReshetka.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Security.Claims;

namespace CReshetka.Controllers
{
    [Authorize]
    public class TestingController : Controller
    {
        private readonly ApplicationDbContext _context;
        public TestingController(ILogger<TestingController> logger, ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SortAlgorithms()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SortAlgorithms(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Алгоритмы сортировки");
        }

        [HttpGet]
        public IActionResult BubbleSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult BubbleSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Сортировка пузырьком (Bubble Sort)");
        }
        
        [HttpGet]
        public IActionResult CocktailSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CocktailSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Шейкерная сортировка (Cocktail Sort)");
        }

        [HttpGet]
        public IActionResult InsertionSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult InsertionSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Сортировка вставками (Insertion Sort)");
        }
        
        [HttpGet]
        public IActionResult ShellSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ShellSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Сортировка Шелла (Shell Sort)");
        }
        
        [HttpGet]
        public IActionResult TreeSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult TreeSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Сортировка деревом (Tree Sort)");
        }
        
        [HttpGet]
        public IActionResult HeapSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult HeapSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Сортировка кучей (Heap Sort)");
        }
        
        [HttpGet]
        public IActionResult SelectionSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SelectionSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Сортировка выбором (Selection ort)");
        }
        
        [HttpGet]
        public IActionResult GnomeSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GnomeSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Гномья сортировка (Gnome Sort)");
        }
        
        [HttpGet]
        public IActionResult RadixSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult RadixSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Поразрядная сортировка (Radix Sort)");
        }
        
        [HttpGet]
        public IActionResult MergeSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult MergeSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Сортировка слиянием (Merge Sort)");
        }
        
        [HttpGet]
        public IActionResult QuickSort()
        {
            return View();
        }
        [HttpPost]
        public IActionResult QuickSort(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions)
        {
            return ProcessTestResults(resultTest, resultsMessage, correctAnswers, totalQuestions, "Быстрая сортировка (Quick Sort)");
        }

        [HttpPost]
        public IActionResult ProcessTestResults(bool resultTest, string resultsMessage, int correctAnswers, int totalQuestions, string testName)
        {
            //var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            //var isComplited = _context.TestResults.Any(tr => tr.UserId == userId && tr.NameTest == testName);

            // Проверка, выполнил ли человек тест верно, если так, то только в этом случае
            // обращаемся к БД и смотрим проходил ли пользователь тест ранее
            if (resultTest && !_context.TestResults.Any(tr => tr.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier) && tr.NameTest == testName))
            {
                // Пользователь не проходил тест ранее, записываем результаты
                var testResult = new TestResult
                {
                    Timestamp = DateTime.Now,
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    NameTest = testName
                };
                
                _context.TestResults.Add(testResult);
                _context.SaveChanges();
            }

            ViewBag.ResultsMessage = resultsMessage;
            ViewBag.CorrectAnswers = correctAnswers;
            ViewBag.TotalQuestions = totalQuestions;

            return View("ResultsView");
        }
        [HttpGet]
        public IActionResult ResultsView()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CReshetka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - C.Reshetka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/CReshetka.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C.Reshetka</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Структуры данных</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="Index">Основная информация</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="Array">Массив</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="List">Список</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="LinkedList">Связный список</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="Queue">Очередь</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="Stack">Стек</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="Dictionary">Словарь</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="">Множество сет</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="">хеш таблица</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="">бинарное дерево</a>
                                <a class="dropdown-item" asp-area="" asp-controller="DataStructure" asp-action="">графы</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Алгоритмы сортировки</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="Index">Основная информация</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="BubbleSort">Сортировка пузырьком</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="CocktailSort">Шейкерная сортировка</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="InsertionSort">Cортировка вставками</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="ShellSort">Cортировка Шелла</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="TreeSort">Cортировка деревом</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="HeapSort">Cортировка кучей</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="SelectionSort">Сортировка выбором</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="GnomeSort">Гномья сортировка</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="RadixSort">Поразрядная сортировка</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="MergeSort">Сортировка слиянием</a>
                                <a class="dropdown-item" asp-area="" asp-controller="SortAlgorithms" asp-action="QuickSort">Быстрая сортировка</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Алгоритмы поиска</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="SearchAlgorithms" asp-action="Index">Основная информация</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" onclick="checkLogin()" asp-area="" asp-controller="Testing" asp-action="Index">Тестирование</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="text-align:center">
            &copy; 2024 - CReshetka - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>